version: "3.9"

volumes:
  db:

services:
  babel-web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: jorgeserrano/signa/babel-web:latest
    links:
      - babel-php:php
    env_file: dev.env
    ports:
      - 8080:80
    volumes:
      - ./www/ms_babel:/srv/www/

  babel-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: jorgeserrano/signa/babel-php:latest
    links:
      - babel-queue:redis
    env_file: dev.env
    ports:
      - 9000
    volumes:
      - ./www/ms_babel:/srv/www/

  babel-scheduler:
    build:
      context: .
      dockerfile: docker/scheduler/Dockerfile
    image: jorgeserrano/signa/babel-scheduler:latest
    links:
      - babel-queue:redis
    env_file: dev.env
    volumes:
      - ./www/ms_babel:/srv/www/   

  babel-db:
    image: mysql:5.7
    ports:
      - 3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
      - db:/var/lib/mysql
    env_file: dev.env

  babel-queue:
    image: redis:7.0-alpine